### ISSUE TITLE
**Code Model Demo**

### ISSUE THREAD

**Issue by ncoop57** [CodedotAl/gpt-code-clippy#4]
- [x] How will we demo the model?

**Comment by neubig** [comment]
I think an online interface would be good, perhaps huggingface could host something on the Write With Transformer site?

Also, separately from this, we have a PyCharm plugin for displaying code generation/retrieval results (https://github.com/neulab/tranx-plugin). It might be fun to incorporate whatever we build here into that so you can actually use it in your coding like copilot. Of course, serving big models like this, latency, etc. would be an issue. But It might be the quickest path to an open-source copilot.

**Comment by urialon** [comment]
We have a web interface at 
https://anycodegen.org/

If it's relevant, I can check if I can provide the frontend's code (the reason I'm not sure and need to check is because I didn't create the frontend, we hired  an external developer)

**Comment by ncoop57** [comment]
I wrote a vscode extension that uses GPT-Neo via HF's inference API that i think we could improve and use. That way it can be very similar to copilot
