### ISSUE TITLE
Vim Plugin

### ISSUE THREAD

**Issue by Shahin-rmz** [CodedotAl/gpt-code-clippy#58]
Awesome work,
I try to begin developing vim plugin version of the project ( if my knowledge allows it).
BTW, awesome job.

**Comment by ncoop57** [comment]
That's awesome I recommend checking out our vs code extension to see how you might use a similar process for a Vim plugin: https://github.com/ncoop57/code-clippy-vscode

**Comment by luisdavim** [comment]
Maybe converting the vscode extension to a coc extension might be easier. https://github.com/neoclide/coc.nvim
https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions

**Comment by Shahin-rmz** [comment]
It's for first time that I've heqrd about coc.
Thanks
