### ISSUE TITLE
Please publish the VS Code extension to OpenVSX as well

### ISSUE THREAD

**Issue by jankeromnes** [CodedotAl/gpt-code-clippy#59]
Hi!

Many thanks for working towards an open-source version of GitHub Copilot. 🙏

I'm particularly interested in the VS Code extension -- could you please also publish it to [OpenVSX](https://open-vsx.org), the open-source, vendor-neutral IDE extension repository?

This would allow users of non-Microsoft products to install this extension as well (for example users of VSCodium, Gitpod, Theia, etc.)

The process should be pretty easy, especially since you already have a VS Code extension (OpenVSX uses the same publishing tools). Please:

1. Generate a [token](https://open-vsx.org/user-settings/tokens)

2. Run `npx ovsx publish`

(That's it.)

**Comment by ncoop57** [comment]
Pretty awesome proj. I tried getting it in, but when I made an eclipse account I kept getting errors :/. If I can figure that out I'll do my best to upload it. Also, just a heads up, vscode extension specific questions or discussions should be put here: https://github.com/ncoop57/code-clippy-vscode
