### ISSUE TITLE
https://huggingface.co/spaces/flax-community/code-clippy-problem-solver gets stuck on generating solution

### ISSUE THREAD

**Issue by allthingssecurity** [CodedotAl/gpt-code-clippy#66]
Was trying this spaces example https://huggingface.co/spaces/flax-community/code-clippy-problem-solver and it seems to get stuck for A function that prints prime numbers from 1 to 100

**Comment by demongolem-biz** [comment]
It gets stuck for me on the example greet problem.  I have tried several other simple problems, and I never get an answer.  It is always "generating solution"

**Comment by reshinthadithyan** [comment]
Thanks for notifying the issue. We are looking into it.

**Comment by ncoop57** [comment]
Not exactly sure what changed, but the demo seems to be working now!

<img src="https://user-images.githubusercontent.com/7613470/136657654-4acedadc-b24f-4224-97e1-9ba158ca7bfd.png" class="img-responsive" alt=""> </div>
