### ISSUE TITLE
how can a normal coder use this ???/ no option give??? how 

### ISSUE THREAD

**Issue by fisforfaheem** [CodedotAl/gpt-code-clippy#67]

**Comment by ahmednrana** [comment]
Please give us a procedure to use it

**Comment by ncoop57** [comment]
If you'd like to use this as a developer (I don't recommend it for any other than curiosity though as it is very untested), you can checkout this vscode extension :nerd_face: ! https://github.com/CodedotAl/code-clippy-vscode

**Comment by fisforfaheem** [comment]
thanks i am a dev! flutter



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality10&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality10&>
09/27/21,
10:34:22 PM

**Comment by fisforfaheem** [comment]
wont use it... very very dofficult to use



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality7&>
Sender
notified by Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality7&>
09/27/21,
10:35:27 PM
