### ISSUE TITLE
Why GPT-CC is lower than CodeX significantly.

### ISSUE THREAD

**Issue by BitcoinNLPer** [CodedotAl/gpt-code-clippy#73]
This is Codex results
![image](https://user-images.githubusercontent.com/84262181/139406446-254257ea-4cf9-47e9-8b91-bcb0c0f231ef.png)

The following result is GPT-CC
![image](https://user-images.githubusercontent.com/84262181/139406526-8fe7f262-8eb4-4b77-8df0-f9ada390e692.png)

- Is it caused by the quality of the pre-trained corpus data?

Thanks

**Comment by Symbolk** [comment]
Also curious, as I know, the HumanEval dataset contains 164 problems, according to the latest result in README, the model does not even pass any one of them!

![image](https://user-images.githubusercontent.com/14107297/149933833-38bfd570-43a5-4b64-a608-cb324ebe8a86.png)

**Comment by taisazero** [comment]
Ya that's correct we discovered issues with the pre-training corpus data. We fixed the issue and released a new pertaining [corpus](https://huggingface.co/datasets/CodedotAI/code_clippy_github) and are in the process of processing the dataset further and pre-training a new GPT-CC.

In the meantime, check out these awesome models: [https://huggingface.co/spaces/codeparrot/code-generation-models](https://huggingface.co/spaces/codeparrot/code-generation-models)
