### ISSUE TITLE
when I run train script, an errors occurs

### ISSUE THREAD

**Issue by BitcoinNLPer** [CodedotAl/gpt-code-clippy#74]
When I run [this train script](https://huggingface.co/flax-community/gpt-neo-125M-code-clippy#training-procedure), I encounter some errors.  The error log is as follows: 
![image](https://user-images.githubusercontent.com/84262181/139572122-c08f3c3f-da86-43a6-859e-9a8ac250098a.png)

Do you know how to solve it?

Furthermore. there are too many files in [code_clippy_data file](https://the-eye.eu/public/AI/training_data/code_clippy_data/). Is there a script to download this dataset conveniently?

**Comment by reshinthadithyan** [comment]
Hello. As we discussed, this is a python specific error. You'll have to reset your recursion limit to some higher number.
Refer [here](https://stackoverflow.com/questions/3323001/what-is-the-maximum-recursion-depth-in-python-and-how-to-increase-it). Feel free to re-open the issue if something pops up. Thanks.

**Comment by BitcoinNLPer** [comment]
Hi, I increased the number of layers for the file with the error, and found that the error is still reported. I want to ask two questions.
![image](https://user-images.githubusercontent.com/84262181/139577045-f36842f5-5d1d-45bb-a73c-6e67218dbd6c.png)

- May I just clone this project and install the corresponding library, and then I can run run_clm_streaming_flax.py? Do I need to download more than 200g of training corpus into my local server? Or does it download automatically? Can you provide a more detailed pre-training guide?
- The server I use has a GPU, so why do I run run_clm_streaming_flax.py directly and use the CPU by default?
![image](https://user-images.githubusercontent.com/84262181/139577131-dc65d4a4-8dd8-4e39-b8aa-a30160ae1395.png)

Thanks!
