### ISSUE TITLE
data cannot download?

### ISSUE THREAD

**Issue by cdj0311** [CodedotAl/gpt-code-clippy#78]
the dataset cannot download: https://the-eye.eu/public/AI/training_data/code_clippy_data/

**Comment by reshinthadithyan** [comment]
Hello. This is a known issue. the-eye has been having issues for sometime now. We are moving the data to huggingface hub, soon. We'll let you know once it's done. Should be done in a week or two.

**Comment by cdj0311** [comment]
> Hello. This is a known issue. the-eye has been having issues for sometime now. We are moving the data to huggingface hub, soon. We'll let you know once it's done. Should be done in a week or two.

Ok，Thanks！
