### ISSUE TITLE
Huggingface example

### ISSUE THREAD

**Issue by Penguin-jpg** [CodedotAl/gpt-code-clippy#79]
Hello, I found this amazing repository today. I tried to run the example found in the huggingface on google colab but it didn't output anything except "Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.". I want to know if there is anything I did wrong. Thanks! (sorry for my poor english)

this is the example:
![image](https://user-images.githubusercontent.com/69071861/156870848-f64221fa-8e97-4596-841e-4e6bffd25f7b.png)

this the code I ran on colab( I change the variable device to "cpu"):
![image](https://user-images.githubusercontent.com/69071861/156870933-3718870d-a58b-4f56-a693-df3db3fbf334.png)

**Comment by arampacha** [comment]
Hi, this is a trivial notification, nothing to worry about.
`generate` method used `pad_token_id` to "understand" that output is and break the generation. If no it's not defined for tokenizer, `eos_token_id` is used. You should be able avoid this notification by either setting it manually:
```py
tokenizer.pad_token_id = tokenizer.eos_token_id
```
or by passing it to `generate` call:
```py
model.generate(..., pad_token_id=tokenizer.eos_token_id
```
