### ISSUE TITLE
how does it compare with GitHub copilot?

### ISSUE THREAD

**Issue by smith-co** [CodedotAl/gpt-code-clippy#80]
How is this implementation comparable with the github copilot and codex model?

**Comment by smith-co** [comment]
@ncoop57 wondering what's your thought about it?

**Comment by taisazero** [comment]
See [https://github.com/CodedotAl/gpt-code-clippy/issues/73](https://github.com/CodedotAl/gpt-code-clippy/issues/73). Hope it helps!
