### ISSUE TITLE
gpt-neo-125M-code-clippy example on huggingface produces empty result

### ISSUE THREAD

**Issue by zupatisc** [CodedotAl/gpt-code-clippy#82]
Not quite sure where to leave this but I wanted to try out this project without training the model myself and found [this model](https://huggingface.co/flax-community/gpt-neo-125M-code-clippy)(It's the only working link from the recommended models) and copied the "How to use" example but it only produces a result with linebreaks in it. Is this expected?

**Comment by taisazero** [comment]
Does it give you an empty result in our 🤗 [Space](https://huggingface.co/spaces/flax-community/code-clippy-problem-solver). If not, use this [model](https://huggingface.co/flax-community/gpt-neo-125M-apps-all) instead. Feel free to re-open the issue if this does not solve it!
